global using AutenticacaoMarcus.SharedKernel;
global using AutenticacaoMarcus.SharedKernel.Retornos;
global using AutenticacaoMarcus.SharedKernel.Extensions;
global using static AutenticacaoMarcus.SharedKernel.Extensions.AspNetCoreExtensions;
global using static AutenticacaoMarcus.SharedKernel.Extensions.EnumExtensions;
global using static AutenticacaoMarcus.SharedKernel.Extensions.StringExtensions;