global using AutenticacaoMarcusApi.SharedKernel;
global using AutenticacaoMarcusApi.SharedKernel.Retornos;
global using AutenticacaoMarcusApi.SharedKernel.Extensions;
global using static AutenticacaoMarcusApi.SharedKernel.Extensions.AspNetCoreExtensions;
global using static AutenticacaoMarcusApi.SharedKernel.Extensions.EnumExtensions;
global using static AutenticacaoMarcusApi.SharedKernel.Extensions.StringExtensions;